jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy: "loggedInUsersCanDoAnything"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  mode: NORMAL
  myViewsTabBar: "standard"
  nodes:
    - permanent:
        launcher:
          ssh:
            credentialsId: "java-agent-ssh-private-key"
            host: "java-agent"
            launchTimeoutSeconds: 210
            maxNumRetries: 10
            port: 22
            retryWaitTime: 15
            jvmOptions: "-agentlib:jdwp=transport=dt_socket,address=8001,suspend=n,server=y"
        name: "java-agent"
        numExecutors: 1
        remoteFS: "/var/data"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
  slaveAgentPort: 50000
  systemMessage: "<h1>Warnings Next Generation Plugin Showcase</h1>"
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  viewsTabBar: "standard"

security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              id: "java-agent-ssh-private-key"
              privateKeySource:
                directEntry:
                  privateKey: "-----BEGIN RSA PRIVATE KEY----- \n
              MIIEowIBAAKCAQEA86cZk1vZh/OwzJDEqga0nnKEh1QpCm1uSDjvuLp2pPDPHMp/ \n
              m9Il9O8ZAZ+IVCUXygO3s1BvBF/a7uVYp7XqjDiTj5Jwrs5lEtl4/1iXXKtwbpAc \n
              bsoiEaFDl7Amc4pUfwzsjaqY4yN4jW+JaLOf/+GqCjwpiyJxZ0N2ONlWoph9dvfH \n
              JBK+LUcbKIqbBAADT12d6ePIBsDn9Yaeem0xSJrwEzcMTFYj6asinMlWgO7VwgZx \n
              JPxhMG+jIq6Mh20tFbwc/XGTqSb/vMkJ8i53RnYm5PoT2xqeYlQCLJtvBRBfuBb5 \n
              WJaQcKvTmLoTgkRCbx/QsQzIWzl4MCj56PRsjQIDAQABAoIBAAGTiy7Q4U9n3DT2 \n
              ms8ey/xacVEO0lUm8Be3hpWDX1Eh3bUp+jlf2q8C/P5tscwZkVXVQFMAqjc1B42U \n
              Hka3fpT5qLq9D82RuEWu8oF0aUZINaoBdK2i0SWcDXvlv9nvgyxvQPiJqgOOLzF7 \n
              D0CGKPrW0urOCNbFmkY4wYMMpOrYXnwb6bc1p7snbzeRigaoGvSgvH7fx2Steg1o \n
              j50C4BKVtXPKQdmckG2SFn0T+U1iCsRG+KNcENX2vX8gyrXImAH093WTjKsmM9et \n
              ddWB+molSnXR/MNrf6BB2mpvXLNyR2/RgBd2jwSQnpDkpms4Br5nek3YYN1dBRL4 \n
              6bofHWECgYEA+7n5OIEbvpMtGxJwOovj0KZMzPkHyQH/DZzo48rS+39goNk/0KLF \n
              c3L3sHbT3Lr4qA/6JOCjlzw7o2AbOrRL4ke1uqcCVQMdDqZdvNezMvTzqEbQGdHD \n
              aFnEcUV2tvEwP11q37ianBRPH5stOnEwQNuv6AJo5LKwi4mTS7qEW9cCgYEA98oJ \n
              h+vMKpXGdJzkSDMzYBrC2tYgqjby6+zGKz8BZ58YecsL+oi2GXBaDTfK+16CKeFM \n
              8+qQN9Kl1ZNOlk64XJXjt77h0FcFuGe+6rUpM1aEizrf9sWPVZO+QQfhnjsiAhtQ \n
              YX783ydy9rMn1FDPMtNNq4GMhGsFCaL4RupOjjsCgYAnk9XbTHFQRVOSLhP3IIdx \n
              BrSMhZrzv5yaR1FWf00svZozr/SYmP7yZ+EJnaUxzzPJOLnbknYmERJPXYzqbe6A \n
              ZUXtUtTLCPJIm1+hkUhbeqfUjU2qwZA3l+WK6aEAomszizyCcEPexlKqZXt29NTh \n
              XakKkVZsnqujRL4j6e9lgQKBgQDvhD8EQJyAyXgkvoc3dy6BBj019WdrwWO9Q4km \n
              wmdkN3gcOnYgvUdwfZa+UiEGLAub2eldmW3AWADu2s5LIlq5PDX7Jir3DTc9UiNM \n
              ksL5mfbS8p0M11i+uupbx/eB0N0FtktTgsGCH4rUBsdIRriSA4h/cOFYGm6rKvnc \n
              6p32gwKBgHZYmXzuBWZlWEmPiXbTaI4egJugur5FrT6BJfiLsN2MHBJi9k1IpKEP \n
              SaT+v0IXJ8jP4gSiu4/gyJQpkn7yiMNhwYWlQt+1zyIkHjUsEG82Z8Mqpjx2EJgG \n
              MxDybQux1uk0hyCmMS757WkbTyi0pTWz7PgTIdfmYqhZVV8KRSUi \n
              -----END RSA PRIVATE KEY----- \n"
              scope: GLOBAL
              username: "agent"
          - gitHubApp:
              appID: "74721"
              description: "GitHub app"
              id: "github-app"
              privateKey:
                directEntry:
                  privateKey: "-----BEGIN PRIVATE KEY----- \n
               MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuHKLwE8ZTtoxd \n
               OgGaGanzI0Dmu2ymJ6DAKycsdRwWaH2PCcml5OtbA0/ZIE3cO3PI3WUQ7JwoowvR \n
               QL35h5PUmn3dtOa9Rfy7Dp7wHfCA4eI+tF+9cn2ojHHEeJ1IMV+JUdPyOcaPpVzX \n
               GMZyZwz4/ZilNZgU8dhPmcLadN985rMn0tky4qm8HfHIdYZtggEFgsFjYVQ0bJVm \n
               sFTxTEz4igojd/HYMDVOEUMZvW1tAPj9eunzv9+q0wo6uN+o4Mm4O9Bjzncyd5oQ \n
               xyAQIL8z3qBh9jaRuCYLk6s6N/mw47kE5LsmoaxApjDWDQaMDoSyg0fk2NFvEXmR \n
               KteDob9FAgMBAAECggEBAIHFiFBmfMkCY8ZMqMsB2+ED4qjXA1koajExOMZzFxdA \n
               lG0bf3etkxpH8qjD4iSHD3qkQWMG6DGFrRYvKimlOrMY3z1zSxPB6WhGsoIH3q1B \n
               L09LQ5zBjBUncNheieQ4IJwKKG3/UBbaysLrjWXRlyKyaaahtpPN2ksiMNCAkd7W \n
               He1HXr7UVpPxp0Ko34BzldcCAd2AHfJ/4dCzIw16oSpmKTnRcog4ikI+nA8GG51o \n
               l0PlKo/b+pYA8JlZW0qZduzJfui8VwLOp4xuFALi657lv3JsZbeDYoWDZG+VvTcy \n
               KiwiR9DOkENLLZK8uSVcz+CNcO4/QS+cl0O9rr3NG8ECgYEA1fJ6KrG7zSUq9r85 \n
               n1wccaLfZdJ4x5XrlJiyTKe7vI9ZSRAxcwXljolofPy5PpUO7Z4Wxl2h4hwrUtNJ \n
               EDZSbg2p5hd4L19eKmLbg1gUjdNXOzUL8M4uBQ9jy9KWQDXjohe470WRfSrrOSRO \n
               ZlL3SNSD7H3bPnvQSHY4QQw6ZrUCgYEA0FWzrwhkQDuGxuCgjWfdeCTtiDsvEAkb \n
               6SDwhypLUDXVZyBqeNaQAaKgOB6b0uErFmxMELwi/5Xmhl/VH4iANdN0+Lmc3vb+ \n
               57nXC3VXpz1Vqbblq5ltw+HCAPDvmsutEo8rMv9r51v7T2qKdCr+On3+bUfOdNuh \n
               S0QP+H/SQFECgYBRwbtVnV264z0r1Z9beoOUGT1tV6S4AF5qBn/8MwzW3aCs/vcm \n
               kVZLxc6cFKdlduihfQwO+bDnCwSzPfJps5iEXcxTFRzkXXlKkUR5SKtyFxT6lybc \n
               +q0zWdI1DWBFYVJ/mrkdFmSmhEQnLeyXxZShzDQtp1qk4gOR7TtKADZBEQKBgQCW \n
               677DKZ0WOwkjwU4NohR6GKZKbjVltHOXqtkT0bvFW3pAvubiquyfgqP2g5X2ak/A \n
               aquf4+qmpHzfE0VdFpFqbMjr9eqCSwPV8naqQlNBP9lynKA8c2Vk5YKZE/E/fhTe \n
               wQBWbVpJvASOP2wVQ5/v154cpEwXs5Ng5ul65330QQKBgFyIa3yglOb+NA/GW8qs \n
               flFsEW8c6aU+5UpKSGijNHUatS1wfR5AXkLKLsFNaD0o7V9PNGhbMyPbOIeACLHw \n
               +8g9RrvKQAWwcKUqP+2elgxEmDLzOm7qmm8mJOswlFGzpNFrfGZ4uCQbIGuoW+C3 \n
               R5GRIthHHZ1hGwx3huudY57S \n
               -----END PRIVATE KEY-----\n"
unclassified:
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED
  location:
    adminAddress: "Adresse nicht konfiguriert <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
  pollSCM:
    pollingThreadCount: 10

tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  maven:
    installations:
      - name: "mvn-default"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.6.3"
  jdk:
    defaultProperties:
      - installSource:
          installers:
            - jdkInstaller:
                acceptLicense: false
  pipelineMaven:
    publisherOptions:
      - jacocoPublisher:
          disabled: true
      - junitPublisher:
          disabled: true
          healthScaleFactor: 1.0
    triggerDownstreamUponResultAborted: false
    triggerDownstreamUponResultFailure: false
    triggerDownstreamUponResultNotBuilt: false
    triggerDownstreamUponResultSuccess: true
    triggerDownstreamUponResultUnstable: false

jobs:
  - script: >
      pipelineJob('pipeline-codingstyle') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/uhafner/codingstyle.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      };
      pipelineJob('pipeline-analysis-model') {
          definition {
              cpsScm {
                  scriptPath 'etc/Jenkinsfile.analysis'
                  scm {
                    git {
                        remote { url 'https://github.com/jenkinsci/analysis-model.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      };
      pipelineJob('pipeline-warnings-ng') {
          definition {
              cpsScm {
                  scriptPath 'etc/Jenkinsfile.analysis'
                  scm {
                    git {
                        remote { url 'https://github.com/jenkinsci/warnings-ng-plugin.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      };
      freeStyleJob('freestyle-warnings-ng') {
          scm {
              git {
                  remote { url 'https://github.com/jenkinsci/warnings-ng-plugin.git' }
                  branch '*/master'
                  extensions {}
              }
          }
          steps {
              maven {
                  mavenInstallation('mvn-default')
                  goals('clean verify')
                  properties(skipITs: true)
              }
          }
          publishers {
              recordIssues {
                  sourceCodeEncoding('UTF-8')
                  aggregatingResults(true)
                  tools {
                      mavenConsole {}
                      java {}
                      javaDoc {}
                      taskScanner {
                          highTags('FIXME')
                          normalTags('TODO')
                          includePattern('**/*.java')
                          excludePattern('target/**/*')
                      }
                      spotBugs {
                            useRankAsPriority(true)
                      }
                      checkStyle {}
                      pmd {}
                      cpd {}
                  }
              }
          }
      };
      freeStyleJob('freestyle-analysis-model') {
          scm {
              git {
                  remote { url 'https://github.com/jenkinsci/analysis-model.git' }
                  branch '*/master'
                  extensions {}
              }
          }
          steps {
              maven {
                  mavenInstallation('mvn-default')
                  goals('clean verify')
                  properties(skipITs: true)
              }
          }
          publishers {
              recordIssues {
                    sourceCodeEncoding('UTF-8')
                    aggregatingResults(true)
                    tools {
                      mavenConsole {}
                      java {}
                      javaDoc {}
                      taskScanner {
                          highTags('FIXME')
                          normalTags('TODO')
                          includePattern('**/*.java')
                          excludePattern('target/**/*')
                      }
                      spotBugs {
                            useRankAsPriority(true)
                      }
                      checkStyle {}
                      pmd {}
                      cpd {}
                  }
              }
        }
      };
